/*
 (c) 2011 (jrj.com)
 @author jianjun.wang@jrj.com.cn
 @version 1.0
*/
if("undefined"==typeof JRJ||!JRJ)var JRJ={};"undefined"!=typeof JRJ.ui&&JRJ.ui||(JRJ.ui={});
(function(){JRJ.ui.Calendar=function(a,b){this._init(a,b)};JRJ.ui.Calendar.prototype={_init:function(a,b){var c=d.$(a);this.id=a;this.config={date:new Date,selected:null,startDay:0,closable:!0,popup:!0,format:"yyyy-mm-dd",yearRange:[1990,2020],disabledDays:null,disabledDates:null,triggerType:"click",minDate:null,maxDate:null,onPicked:null,onYearChanged:null,onMonthCanged:null,validType:"blur",onerror:null};d.mix(this.config,b||{});this.config.popup?(this.trigger=c,this.con=d.createElement("div"),
this.con.id=(new Date).getTime(),d.css(this.con,{display:"none",position:"absolute"}),document.body.appendChild(this.con)):this.con=c;d.addClass(this.con,"jrj-cal-box");this._handleDate();this.selected=this.config.selected;this.config.startDay&&(this.config.startDay=(7-this.config.startDay)%7);this._value=null;this.render();this._bindEvent()},_bindEvent:function(){var a=this;a.config.popup&&(e.on(document.body,"click",function(b){b=e.getTarget(b);if(b.id!=a.id&&"hidden"!=a.con.style.visibility){a:{for(;null!=
b&&"undefind"!=typeof b.tagName;){if(b==a.con){b=!0;break a}b=b.parentNode}b=!1}b||a.hide()}}),e.on(a.trigger,a.config.triggerType,function(b){e.stop(b);a.toggle()}),e.on(a.trigger,a.config.validType,function(b){try{p.format(a.trigger.value,a.config.format)}catch(c){if(a._value&&(a.trigger.value=a._value,a.config.onerror))a.config.onerror()}}))},toggle:function(){"none"==this.con.style.display?(this.echoInputDate(),this.show()):this.hide()},echoInputDate:function(){isNaN(d.parseISO8601(this.trigger.value).getDay())?
this.config.date=this.selected=new Date:this.config.date=this.selected=d.parseISO8601(this.trigger.value);this._handleDate();this.render()},show:function(){var a=d.getOffsetPosition(this.trigger),b=a.left,a=a.top+this.trigger.offsetHeight||window.getComputedStyle(this.trigger,null).getPropertyValue("height");d.css(this.con,{left:b+"px",top:a+"px",display:""})},hide:function(){var a=this;setTimeout(function(){d.getElementsByClassName(a.con,"jrj-cal-year-list")[0].style.display="none";d.getElementsByClassName(a.con,
"jrj-cal-month-list")[0].style.display="none"},0);a.con.style.display="none"},render:function(a){this._renderUI();this._bindUIEvent();return this},_renderUI:function(){this.html=['<div class="jrj-cal-hd"><a href="javascript:void(0)" class="jrj-cal-prev" title="\u4e0a\u6708"><span>\u4e0a\u6708</span></a><div class="jrj-cal-year"><span>{$year}\u5e74</span><p class="jrj-cal-year-list" style="display:none">',this.createYearList(),'</p></div><div class="jrj-cal-month"><span>{$month}\u6708</span><p class="jrj-cal-month-list" style="display:none"><i>1</i><i>2</i><i>3</i><i>4</i><i>5</i><i>6</i><i>7</i><i>8</i><i>9</i><i>10</i><i>11</i><i>12</i></p></div><a href="javascript:void(0)" class="jrj-cal-next" title="\u4e0b\u6708"><span>\u4e0b\u6708</span></a></div><div class="jrj-cal-bd"><div class="jrj-cal-whd jrj-clear">',
this._handleDayOffset(),'</div><div class="jrj-cal-dbd jrj-clear">',this.createDaysHtml(),"</div></div>"].join("");this.html=this.html.replace("{$year}",this.year);this.html=this.html.replace("{$month}",this.month+1);this.con.innerHTML=this.html},_bindUIEvent:function(){var a=this,b=d.getElementsByClassName(a.con,"jrj-cal-year")[0],c=b.firstChild,f=d.getElementsByClassName(a.con,"jrj-cal-year-list")[0],q=b.getElementsByTagName("i"),h=d.getElementsByClassName(a.con,"jrj-cal-month")[0],l=h.firstChild,
g=d.getElementsByClassName(a.con,"jrj-cal-month-list")[0],m=h.getElementsByTagName("i");e.on(b,"click",function(b){e.stop(b);if("none"==f.style.display){if(f.style.display="",a.selected)for(b=0;b<q.length;b++)if(q[b].innerHTML==a.year){q[b].className="hover";var c=q[b].offsetTop;setTimeout(function(){f.scrollTop=c},0)}}else f.style.display="none";g.style.display="none"});for(b=0;b<q.length;b++)e.on(q[b],"click",function(b){e.stop(b);b=e.getTarget(b);b=parseInt(b.innerHTML,10);c.innerHTML=b;a.year=
b;f.style.display="none";a.render();if(d.isFunction(a.config.onYearChange))a.config.onYearChange(a.year)}),d.ie6&&(e.on(q[b],"mouseover",function(a){e.getTarget(a).className="hover"}),e.on(q[b],"mouseout",function(a){e.getTarget(a).className=""}));e.on(h,"click",function(b){e.stop(b);if("none"==g.style.display){if(g.style.display="",a.selected)for(b=0;b<m.length;b++)if(m[b].innerHTML==a.month+1){m[b].className="hover";var c=m[b].offsetTop;setTimeout(function(){g.scrollTop=c},0)}}else g.style.display=
"none";f.style.display="none"});for(b=0;b<m.length;b++)e.on(m[b],"click",function(b){e.stop(b);b=e.getTarget(b);b=parseInt(b.innerHTML,10);l.innerHTML=b;a.month=b-1;g.style.display="none";a.render();if(d.isFunction(a.config.onMonthChange))a.config.onMonthChange(a.month+1)}),d.ie6&&(e.on(m[b],"mouseover",function(a){e.getTarget(a).className="hover"}),e.on(m[b],"mouseout",function(a){e.getTarget(a).className=""}));h=d.getElementsByClassName(a.con,"jrj-cal-prev")[0];b=d.getElementsByClassName(a.con,
"jrj-cal-next")[0];e.on(h,"click",function(b){e.stop(b);a._monthMinus().render();c.innerHTML=a.year+"\u5e74";l.innerHTML=a.month+1+"\u6708";if(d.isFunction(a.config.onMonthChange))a.config.onMonthChange(a.month+1)});e.on(b,"click",function(b){e.stop(b);a._monthAdd().render();c.innerHTML=a.year+"\u5e74";l.innerHTML=a.month+1+"\u6708";if(d.isFunction(a.config.onMonthChange))a.config.onMonthChange(a.month+1)});h=d.getElementsByClassName(a.con,"jrj-cal-dbd")[0];e.on(h,"click",function(b){e.stop(b);b=
e.getTarget(b);if(d.hasClass(b,"jrj-cal-dbd")||d.hasClass(b,"jrj-cal-null")||d.hasClass(b,"jrj-cal-disabled"))return!1;b=parseInt(b.innerHTML,10);var c=new Date("2011/01/01");c.setDate(b);c.setYear(a.year);c.setMonth(a.month);a.selected=c;a.trigger&&"INPUT"==a.trigger.tagName.toUpperCase()&&"text"==a.trigger.type&&(a.trigger.value=p.format(c,a.config.format),a._value=a.trigger.value);if(d.isFunction(a.config.onPicked))a.config.onPicked(c);a.config.popup&&a.config.closable&&a.hide();a.render()})},
_monthAdd:function(){11==this.month?(this.month=0,this.year++):this.month++;this.date=new Date(this.year+"/"+(this.month+1)+"/01");return this},_monthMinus:function(){0==this.month?(this.month=11,this.year--):this.month--;this.date=new Date(this.year+"/"+(this.month+1)+"/01");return this},_computeNextMonth:function(a){var b=a[0];a=a[1];11==a?(b++,a=0):a++;return[b,a]},_computePreviousMonth:function(){},_handleDate:function(){var a=this.config.date;this.weekday=a.getDay()+1;this.day=a.getDate();this.month=
a.getMonth();this.year=a.getFullYear();return this},_handleDayOffset:function(){for(var a="\u65e5\u4e00\u4e8c\u4e09\u56db\u4e94\u516d".split(""),b=this.config.startDay,c="",f=0;7>f;f++)c+="<span>{$day}</span>".replace("{$day}",a[(f-b+7)%7]);return c},_getNumOfDays:function(a,b){return 32-(new Date(a,b-1,32)).getDate()},createDaysHtml:function(){var a=this.config,b="",c=((new Date(this.year+"/"+(this.month+1)+"/01")).getDay()+a.startDay+7)%7,f=this._getNumOfDays(this.year,this.month+1)+c,e=new Date,
h,l,g="";for(h=0;a.disabledDates&&h<a.disabledDates.length;h++)g+=p.format(a.disabledDates[h],"isoDate")+",";for(h=0;h<f;h++)l=h-c+1,b=h<c?b+'<a class="jrj-cal-null" href="javascript:void(0)">0</a>':a.minDate instanceof Date&&(new Date(this.year+"/"+(this.month+1)+"/"+l)).getTime()<a.minDate.getTime()?b+('<a class="jrj-cal-disabled" href="javascript:void(0)">'+l+"</a>"):a.maxDate instanceof Date&&(new Date(this.year+"/"+(this.month+1)+"/"+l)).getTime()>a.maxDate.getTime()?b+('<a class="jrj-cal-disabled" href="javascript:void(0)">'+
l+"</a>"):a.disabledDays&&d.contains(a.disabledDays.join(""),(new Date(this.year+"/"+(this.month+1)+"/"+l)).getDay()+"")?b+('<a class="jrj-cal-disabled" href="javascript:void(0)">'+l+"</a>"):a.disabledDates&&d.contains(g,p.format(new Date(this.year+"/"+(this.month+1)+"/"+l),"isoDate"))?b+('<a class="jrj-cal-disabled" href="javascript:void(0)">'+l+"</a>"):l==e.getDate()&&e.getFullYear()==this.year&&e.getMonth()==this.month?b+('<a class="jrj-cal-today" href="javascript:void(0)">'+l+"</a>"):this.selected&&
l==this.selected.getDate()&&this.year==this.selected.getFullYear()&&this.month==this.selected.getMonth()?b+('<a class="jrj-cal-selected" href="javascript:void(0)">'+l+"</a>"):b+('<a href="javascript:void(0)">'+l+"</a>");if(0!==f%7)for(h=0;h<7-f%7;h++)b+='<a class="jrj-cal-null" href="javascript:void(0)">0</a>';return b},createYearList:function(){for(var a=this.config.yearRange,b="",c=a[1];c>=a[0];c--)b+="<i>"+c+"</i>";return b}};var e={on:function(a,b,c){d.isDefined(a,"attachEvent")?a.attachEvent("on"+
b,function(a){c(a)}):d.isDefined(a,"addEventListener")&&a.addEventListener(b,c,!1);return[a,b,c]},remove:function(a){d.isDefined(a[0],"detachEvent")?a[0].detachEvent("on"+a[1],a[2]):d.isDefined(a[0],"removeEventListener")&&a[0].removeEventListener(a[1],a[2],!1)},bindAsEvent:function(a,b,c){return function(f){b.apply(a,[f||window.event].concat(c))}},getTarget:function(a){return null==a?null:"undefined"!=typeof a.srcElement?a.srcElement:a.target},stop:function(a){document.all?(a.returnValue=!1,a.cancelBubble=
!0):(a.preventDefault(),a.stopPropagation())},pageXY:function(a){return{left:a.pageX||a.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft),top:a.pageY||a.clientY+(document.documentElement.scrollTop||document.body.scrollTop)}}},A=navigator.userAgent.toLowerCase(),d={ie:!1,ie6:-1!=navigator.appVersion.indexOf("MSIE 6.0"),isWebkit:/applewebkit/.test(A),$:function(a,b){if(!b)var c=document;return c.getElementById(a)},getElementsByClassName:function(a,b){var c=function(a,b,f){if(a.hasChildNodes())for(var g=
a.childNodes,d=0;d<g.length;c(g[d],b,f),d++);try{if(null!=a.className)for(var e=a.className.split(" "),d=0;d<e.length;e[d]==b?f.push(a):null,d++);}catch(n){}},f=[];c(a,b,f);return f},isDefined:function(a,b){return"undefined"!=typeof a[b]},isFunction:function(a){return!!(a&&a.constructor&&a.call&&a.apply)},createElement:function(a,b){if(!b)var c=document;return c.createElement(a)},css:function(a,b){var c=a.style,f;for(f in b)c[f]=b[f]},getOffsetPosition:function(a){if(!a)return{left:0,top:0};var b=
0,c=0;if("getBoundingClientRect"in document.documentElement){c=a.getBoundingClientRect();b=a.ownerDocument;a=b.body;var f=b.documentElement,d=f.clientLeft||a.clientLeft||0,b=c.top+(self.pageYOffset||f&&f.scrollTop||a.scrollTop)-(f.clientTop||a.clientTop||0),c=c.left+(self.pageXOffset||f&&f.scrollLeft||a.scrollLeft)-d}else{do b+=a.offsetTop||0,c+=a.offsetLeft||0,a=a.offsetParent;while(a)}return{left:c,top:b}},trim:function(a){return a.replace(/(^\s*)|(\s*$)/g,"")},contains:function(a,b){return-1<a.toLowerCase().indexOf(b.toLowerCase())},
hasClass:function(a,b){return a.className.match(new RegExp("(\\s|^)"+b+"(\\s|$)"))},addClass:function(a,b){this.hasClass(a,b)||(a.className+=" "+b)},removeClass:function(a,b){this.hasClass(a,b)&&(a.className=a.className.replace(new RegExp("(\\s|^)"+b+"(\\s|$)")," "))},mix:function(a,b){for(k in b)void 0!==b[k]&&(a[k]=b[k]);return a},parseISO8601:function(a){var b=new Date(NaN),c=/^\s*(\d{4})-(\d\d)-(\d\d)\s*$/.exec(a);c&&(a=+c[2],b.setFullYear(c[1],a-1,c[3]),a!=b.getMonth()+1&&b.setTime(NaN));return b}},
B=function(){var a=/w{1}|d{1,4}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|[LloSZ]|"[^"]*"|'[^']*'/g,b=/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g,c=/[^-+\dA-Z]/g,d=function(a,b){a=String(a);for(b=b||2;a.length<b;)a="0"+a;return a},e={"default":"ddd mmm dd yyyy HH:MM:ss",shortDate:"m/d/yy",longDate:"mmmm d, yyyy",fullDate:"dddd, mmmm d, yyyy",shortTime:"h:MM TT",longTime:"h:MM:ss TT Z",isoDate:"yyyy-mm-dd",isoTime:"HH:MM:ss",
isoDateTime:"yyyy-mm-dd'T'HH:MM:ss",isoUTCDateTime:"UTC:yyyy-mm-dd'T'HH:MM:ss'Z'",localShortDate:"yy\u5e74mm\u6708dd\u65e5",localShortDateTime:"yy\u5e74mm\u6708dd\u65e5 hh:MM:ss TT",localLongDate:"yyyy\u5e74mm\u6708dd\u65e5",localLongDateTime:"yyyy\u5e74mm\u6708dd\u65e5 hh:MM:ss TT",localFullDate:"yyyy\u5e74mm\u6708dd\u65e5 w",localFullDateTime:"yyyy\u5e74mm\u6708dd\u65e5 w hh:MM:ss TT"},h="Sun Mon Tue Wed Thu Fri Sat Sunday Monday Tuesday Wednesday Thursday Friday Saturday \u661f\u671f\u65e5 \u661f\u671f\u4e00 \u661f\u671f\u4e8c \u661f\u671f\u4e09 \u661f\u671f\u56db \u661f\u671f\u4e94 \u661f\u671f\u516d".split(" "),
l="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec January February March April May June July August September October November December".split(" ");return function(g,m,p){1!=arguments.length||"[object String]"!=Object.prototype.toString.call(g)||/\d/.test(g)||(m=g,g=void 0);g=g?new Date(g):new Date;if(isNaN(g))throw SyntaxError("invalid date");m=String(e[m]||m||e["default"]);"UTC:"==m.slice(0,4)&&(m=m.slice(4),p=!0);var n=p?"getUTC":"get",s=g[n+"Date"](),u=g[n+"Day"](),t=g[n+"Month"](),w=g[n+"FullYear"](),
r=g[n+"Hours"](),x=g[n+"Minutes"](),y=g[n+"Seconds"](),n=g[n+"Milliseconds"](),v=p?0:g.getTimezoneOffset(),z={d:s,dd:d(s),ddd:h[u],dddd:h[u+7],w:h[u+14],m:t+1,mm:d(t+1),mmm:l[t],mmmm:l[t+12],yy:String(w).slice(2),yyyy:w,h:r%12||12,hh:d(r%12||12),H:r,HH:d(r),M:x,MM:d(x),s:y,ss:d(y),l:d(n,3),L:d(99<n?Math.round(n/10):n),t:12>r?"a":"p",tt:12>r?"am":"pm",T:12>r?"A":"P",TT:12>r?"AM":"PM",Z:p?"UTC":(String(g).match(b)||[""]).pop().replace(c,""),o:(0<v?"-":"+")+d(100*Math.floor(Math.abs(v)/60)+Math.abs(v)%
60,4),S:["th","st","nd","rd"][3<s%10?0:(10!=s%100-s%10)*s%10]};return m.replace(a,function(a){return a in z?z[a]:a.slice(1,a.length-1)})}}(),p={format:function(a,b,c){return B(a,b,c)},parse:function(a){var b=null;b instanceof Date?a=b:(b=new Date(a),a=b instanceof Date&&"Invalid Date"!=b&&!isNaN(b)?b:null);return a}}})();
