document.writeln("<style type=\"text/css\">");
document.writeln(".header{padding-top:31px;_padding-top:0}");
document.writeln(".enter{position:fixed;top:0;left:0;width:100%;z-index:7000}");
document.writeln("</style>");
document.writeln("<div class=\"enter\">");
document.writeln("		<div class=\"enbn\">");
document.writeln("			<div class=\"en_left\">");
//document.writeln("				<a href=\"javascript:JRJ.bom.addBookmark(window.location,\'金融界：中国财经金融门户\')\" class=\"linktop01\"  target=\"_self\">收藏金融界</a><i>|</i><a href=\"http://www.jrj.com.cn/\">金融界首页</a>");
document.writeln("				<span class=\"en_left-inner\"><a href=\"http://www.jrj.com.cn/\" target=\"_blank\">金融界首页</a><i>|</i><a href=\"http://finance.jrj.com.cn/\" target=\"_blank\">资讯</a><i>|</i><a href=\"http://stock.jrj.com.cn/\" target=\"_blank\">股票</a><i>|</i><a href=\"http://fund.jrj.com.cn/\" target=\"_blank\">基金</a><i>|</i><a href=\"http://gold.jrj.com.cn/\" target=\"_blank\">贵金属</a><i>|</i><a href=\"http://insurance.jrj.com.cn/\" target=\"_blank\">保险</a><i>|</i><a href=\"http://bank.jrj.com.cn/\" target=\"_blank\">银行</a></span>");
document.writeln('				<div class="en_left-inner dropdownlist dropdownlist-more">');
document.writeln('				    <i></i>');
document.writeln('				    <span>更多</span>');
document.writeln('				    <ul>');
document.writeln('				        <li>更多</li>');
document.writeln('				        <li><a href="http://blog.jrj.com.cn/" target=\"_blank\">博客</a></li>');
document.writeln('				        <li><a href="http://bbs.jrj.com.cn/" target=\"_blank\">论坛</a></li>');
document.writeln('				    </ul>');
document.writeln('				</div>');
document.writeln('				<div class="en_left-inner">');
document.writeln('				    <a href=\"http://www.jrj.com.cn/sitemap.shtml\" target=\"_blank\">网站地图</a>');
document.writeln('				</div>');
document.writeln("			</div>");
document.writeln('			<div class="en_right" id="header_wiget_placeholder">');
document.writeln("			</div>");
document.writeln("			<div class=\"en_right\">");
document.writeln("				<div class=\"login\" id=\"loginbefore\">");
document.writeln('				    <a  target="_self" href="http://sso.jrj.com.cn/sso/ssologin?ReturnURL='+location.href+'">登录</a><i>|</i><a href="http://i.jrj.com.cn/register.faces?ReturnURL='+location.href+'">注册</a>');
document.writeln("					<label style=\"display:none\"><span>用户名：</span><input type=\"text\" class=\"tx\" id=\"LoginID\" /></label>");
document.writeln("					<label style=\"display:none\"><span>密　码：</span><input type=\"password\" class=\"tx\"id=\"Passwd\" /></label>");
document.writeln("					<a style=\"display:none\" href=\"javascript:void(0)\" target=\"_self\" id=\"ssoLogin\">[登录]</a>");
document.writeln("					<a style=\"display:none\" href=\"http://i.jrj.com.cn/register.faces?SysID=www.jrj.com.cn\">[5秒注册]</a>");
document.writeln("					<a style=\"display:none\" href=\"http://i.jrj.com.cn/retrievePWD.faces\">[忘记密码]</a>");
document.writeln("				</div>");
document.writeln("				<div class=\"loginnew\" id=\"loginafter\" style=\"display:none\">");
document.writeln("					<ul class=\"jrj-clear\">");
document.writeln("					<li><span>您好,</span></li>");
document.writeln("					<li><a href=\"\" class=\"username\"></a></li>");
document.writeln("					<li><a href=\"\">退出</a></li>");
document.writeln("					</ul>");
document.writeln("					<span class=\"nub\">消息(<b>0</b>)</span>");
document.writeln("				</div>");
//document.writeln("				<div class=\"login-ty\"><i>|</i><a href=\"http://www.m.jrj.com.cn/\" class=\"linktop02\">手机金融界</a><i>|</i><a href=\"http://www.jrj.com.cn/sitemap.shtml\" class=\"linktop03\">网站导航</a></div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");